### PR TITLE
Update contributions.md

### PR DESCRIPTION
**Pull request by leandro-liborio**
We need to make the 'contributions section' visible in the MSCP's webpage

### CODE REVIEW

**Comment by patrick-austin** [comment]
Adding contributions.html to `default.html` results in:
image
Can re-order if needed.

**Comment by leandro-liborio** [comment]
what do you mean re-order?

**Comment by patrick-austin** [comment]
> what do you mean re-order?

I added "Contributing" to the bottom of the list in the navigation pane, but can put it somewhere else if we want (or re-order the others). For example between "Software" and "Funding".

**Comment by leandro-liborio** [comment]
I think at the bottom is OK.

**Review by subindev-d — APPROVED** [review]

**Pull request merged**
